# Generated by Django 4.1.3 on 2022-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('post_body', models.TextField()),
            ],
        ),
    ]
