# Generated by Django 4.1.3 on 2022-12-06 18:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
