# Generated by Django 4.1.4 on 2022-12-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(verbose_name='last updated'),
        ),
    ]
